FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Build arguments for environment variables
ARG VITE_BASE_URL
ARG VITE_WS_URL
ARG VITE_API_URL

# Set environment variables for build
ENV VITE_BASE_URL=${VITE_BASE_URL}
ENV VITE_WS_URL=$VITE_WS_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "start"]
